### ISSUE TITLE
ERROR:  column "Fires.point" must appear in the GROUP BY clause or be used in an aggregate function

### ISSUE THREAD

**Issue by rahulbreezo** [bytesandbrains/h3-pg#62]
Hey , 

I have fires recorded data.
I want to create a materialized table by aggregating fire points grouped by recorded at and h3 index , but When I group them using `h3_geo_to_h3` and add `group by` clause with `recorded_at`, it gives me error:

```
breezo=# select h3_geo_to_h3("Fires"."point" , 1)::point as p, recorded_at, point from "Fires" group by recorded_at limit 1;
ERROR:  column "Fires.point" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: select h3_geo_to_h3("Fires"."point" , 1)::point as p, record...
```

I have tried few of postgis aggregate function , but they did not help, 
It will be grateful , if someone could help me here .

Thanks,

**Comment by dfellis** [comment]
Hi, I don't work on this project, but I do watch it. I think this tutorial on Postgres' `group by` syntax will help: https://sqlserverguides.com/postgresql-group-by/

Basically, every column that you include in the select list also needs to be in the group by list, in the sorting priority order, except if you're passing that column to an *aggregate function* (which takes all of the values associated together by having the same group by "index" and passes them all to that function).

`h3_geo_to_h3` is not an aggregating function, so you would need to include `Fires.point` in your `group by` clause, but you *can* also have it inside of the `h3_geo_to_h3` method call, so the finer details of the point can be ignored if you wanted something like that (since you're using H3 Resolution 1, which is a roughly country-sized hexagon resolution):

```sql
select h3_geo_to_h3("Fires"."point", 1)::point as p, recorded_at, COUNT(h3_geo_to_h3("Fires"."point", 1):: point) as fire_count
from "Fires"
group by recorded_at, h3_geo_to_h3("Fires"."point", 1)::point
limit 1
```

This also doesn't care about the actual order of `recorded_at` or other columns, just that the same values are stuck together, so whatever time is the first the Postgresql engine is "sure" is finished is what you'd get, which is probably not what you'd want. I'd also throw in an `order by recorded_at desc` in there to make sure you get the latest record (for instance).

**Comment by rahulbreezo** [comment]
Thanks , adding same function in `group by`  clause works.
